Сдавать ссылкой на github
## Условие 1: Задача 1
Скачать данные по ссылке https://www.kaggle.com/datasets/ionaskel/laptop-prices
Считать данные с помощью pandas
Вывести на экран первые 5 строк

In [123]:
import pandas as pd

df = pd.read_csv('kc_house_data (1).csv', encoding='windows-1251', parse_dates=['date'])
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,2014-10-13,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,2014-12-09,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,2015-02-25,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,2014-12-09,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,2015-02-18,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

### 1.2 Создать новый признак delta_renovated, который будет содержать разницу в годах между годом реновацией дома и годом постройки дома
Если реновации дома не было, то в новом признаке поставьте 0

In [124]:
df['delta_renovated'] = 0
df.loc[df['yr_renovated'] != 0, 'delta_renovated'] = df['yr_renovated'] - df['yr_built']
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,delta_renovated
0,7129300520,2014-10-13,221900.0,3,1.00,1180,5650,1.0,0,0,...,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,0
1,6414100192,2014-12-09,538000.0,3,2.25,2570,7242,2.0,0,0,...,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,40
2,5631500400,2015-02-25,180000.0,2,1.00,770,10000,1.0,0,0,...,770,0,1933,0,98028,47.7379,-122.233,2720,8062,0
3,2487200875,2014-12-09,604000.0,4,3.00,1960,5000,1.0,0,0,...,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,0
4,1954400510,2015-02-18,510000.0,3,2.00,1680,8080,1.0,0,0,...,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,2014-05-21,360000.0,3,2.50,1530,1131,3.0,0,0,...,1530,0,2009,0,98103,47.6993,-122.346,1530,1509,0
21609,6600060120,2015-02-23,400000.0,4,2.50,2310,5813,2.0,0,0,...,2310,0,2014,0,98146,47.5107,-122.362,1830,7200,0
21610,1523300141,2014-06-23,402101.0,2,0.75,1020,1350,2.0,0,0,...,1020,0,2009,0,98144,47.5944,-122.299,1020,2007,0
21611,291310100,2015-01-16,400000.0,3,2.50,1600,2388,2.0,0,0,...,1600,0,2004,0,98027,47.5345,-122.069,1410,1287,0
21612,1523300157,2014-10-15,325000.0,2,0.75,1020,1076,2.0,0,0,...,1020,0,2008,0,98144,47.5941,-122.299,1020,1357,0

### 1.3 Создайте признаки года продажи, месяца продажи

In [125]:
df['yr_sale'] = df['date'].apply(lambda x: x.year)
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,delta_renovated,yr_sale
0,7129300520,2014-10-13,221900.0,3,1.00,1180,5650,1.0,0,0,...,0,1955,0,98178,47.5112,-122.257,1340,5650,0,2014
1,6414100192,2014-12-09,538000.0,3,2.25,2570,7242,2.0,0,0,...,400,1951,1991,98125,47.7210,-122.319,1690,7639,40,2014
2,5631500400,2015-02-25,180000.0,2,1.00,770,10000,1.0,0,0,...,0,1933,0,98028,47.7379,-122.233,2720,8062,0,2015
3,2487200875,2014-12-09,604000.0,4,3.00,1960,5000,1.0,0,0,...,910,1965,0,98136,47.5208,-122.393,1360,5000,0,2014
4,1954400510,2015-02-18,510000.0,3,2.00,1680,8080,1.0,0,0,...,0,1987,0,98074,47.6168,-122.045,1800,7503,0,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,2014-05-21,360000.0,3,2.50,1530,1131,3.0,0,0,...,0,2009,0,98103,47.6993,-122.346,1530,1509,0,2014
21609,6600060120,2015-02-23,400000.0,4,2.50,2310,5813,2.0,0,0,...,0,2014,0,98146,47.5107,-122.362,1830,7200,0,2015
21610,1523300141,2014-06-23,402101.0,2,0.75,1020,1350,2.0,0,0,...,0,2009,0,98144,47.5944,-122.299,1020,2007,0,2014
21611,291310100,2015-01-16,400000.0,3,2.50,1600,2388,2.0,0,0,...,0,2004,0,98027,47.5345,-122.069,1410,1287,0,2015
21612,1523300157,2014-10-15,325000.0,2,0.75,1020,1076,2.0,0,0,...,0,2008,0,98144,47.5941,-122.299,1020,1357,0,2014

In [126]:
df['month_sale'] = df['date'].apply(lambda x: x.month)
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,delta_renovated,yr_sale,month_sale
0,7129300520,2014-10-13,221900.0,3,1.00,1180,5650,1.0,0,0,...,1955,0,98178,47.5112,-122.257,1340,5650,0,2014,10
1,6414100192,2014-12-09,538000.0,3,2.25,2570,7242,2.0,0,0,...,1951,1991,98125,47.7210,-122.319,1690,7639,40,2014,12
2,5631500400,2015-02-25,180000.0,2,1.00,770,10000,1.0,0,0,...,1933,0,98028,47.7379,-122.233,2720,8062,0,2015,2
3,2487200875,2014-12-09,604000.0,4,3.00,1960,5000,1.0,0,0,...,1965,0,98136,47.5208,-122.393,1360,5000,0,2014,12
4,1954400510,2015-02-18,510000.0,3,2.00,1680,8080,1.0,0,0,...,1987,0,98074,47.6168,-122.045,1800,7503,0,2015,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,2014-05-21,360000.0,3,2.50,1530,1131,3.0,0,0,...,2009,0,98103,47.6993,-122.346,1530,1509,0,2014,5
21609,6600060120,2015-02-23,400000.0,4,2.50,2310,5813,2.0,0,0,...,2014,0,98146,47.5107,-122.362,1830,7200,0,2015,2
21610,1523300141,2014-06-23,402101.0,2,0.75,1020,1350,2.0,0,0,...,2009,0,98144,47.5944,-122.299,1020,2007,0,2014,6
21611,291310100,2015-01-16,400000.0,3,2.50,1600,2388,2.0,0,0,...,2004,0,98027,47.5345,-122.069,1410,1287,0,2015,1
21612,1523300157,2014-10-15,325000.0,2,0.75,1020,1076,2.0,0,0,...,2008,0,98144,47.5941,-122.299,1020,1357,0,2014,10

### 1.4 Удалите признаки date, zipcode, lat, long

In [127]:
df.drop(columns=['date', 'zipcode', 'lat', 'long'], inplace=True)
df

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,sqft_living15,sqft_lot15,delta_renovated,yr_sale,month_sale
0,7129300520,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,1340,5650,0,2014,10
1,6414100192,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,1690,7639,40,2014,12
2,5631500400,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,2720,8062,0,2015,2
3,2487200875,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,1360,5000,0,2014,12
4,1954400510,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,1800,7503,0,2015,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,1530,1509,0,2014,5
21609,6600060120,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,1830,7200,0,2015,2
21610,1523300141,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,1020,2007,0,2014,6
21611,291310100,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,1410,1287,0,2015,1
21612,1523300157,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,1020,1357,0,2014,10

## Условие 2: 2 задача
Создайте датафрейм с клиентами:
clients = pd.DataFrame({
'client_id': [1459, 4684, 3498, 3942, 4535, 2308, 2866, 2765, 1472, 4236, 2295,
939, 3840, 280, 20, 4332, 3475, 4213, 3113, 4809, 2134, 2242,
2068, 4929, 1384, 1589, 3317, 2260, 1727, 1764, 1611, 1474],
'house_id': [8965450190, 6823100225, 5104540330, 2131701075, 1522700060,
1189000207, 6821600300, 7137950720, 9510920050, 6131600255,
5428000070, 1788800910, 8100400160, 3123049142, 6306800010,
5083000375, 7920100025, 1951600150, 809001400, 339600110,
1622049154, 1099600250, 8563000110, 2768100205, 3995700435,
8861700030, 3303980210, 7731100066, 8146100580, 825069097,
3889100029, 9524100196]
})

In [133]:
clients = pd.DataFrame({
'client_id': [1459, 4684, 3498, 3942, 4535, 2308, 2866, 2765, 1472, 4236, 2295,
                939, 3840, 280, 20, 4332, 3475, 4213, 3113, 4809, 2134, 2242,
                2068, 4929, 1384, 1589, 3317, 2260, 1727, 1764, 1611, 1474],
'house_id': [8965450190, 6823100225, 5104540330, 2131701075, 1522700060,
            1189000207, 6821600300, 7137950720, 9510920050, 6131600255,
            5428000070, 1788800910, 8100400160, 3123049142, 6306800010,
            5083000375, 7920100025, 1951600150, 809001400, 339600110,
            1622049154, 1099600250, 8563000110, 2768100205, 3995700435,
            8861700030, 3303980210, 7731100066, 8146100580, 825069097,
            3889100029, 9524100196]
})
clients

    client_id    house_id
0        1459  8965450190
1        4684  6823100225
2        3498  5104540330
3        3942  2131701075
4        4535  1522700060
5        2308  1189000207
6        2866  6821600300
7        2765  7137950720
8        1472  9510920050
9        4236  6131600255
10       2295  5428000070
11        939  1788800910
12       3840  8100400160
13        280  3123049142
14         20  6306800010
15       4332  5083000375
16       3475  7920100025
17       4213  1951600150
18       3113   809001400
19       4809   339600110
20       2134  1622049154
21       2242  1099600250
22       2068  8563000110
23       4929  2768100205
24       1384  3995700435
25       1589  8861700030
26       3317  3303980210
27       2260  7731100066
28       1727  8146100580
29       1764   825069097
30       1611  3889100029
31       1474  9524100196

### 2.1 Присоедините к таблице clients данные по домам через метод join

In [134]:
df.set_index('id', inplace=True)
clients.set_index('house_id', inplace=True)
clients.join(df)

,client_id,index,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,sqft_living15,sqft_lot15,delta_renovated,yr_sale,month_sale
339600110,4809,3351,395000.0,3,2.50,1610,3755,2.0,0,0,...,7,1610,0,1987,0,1300,3823,0,2014,9
809001400,3113,9369,925000.0,3,1.00,1630,3200,1.5,0,0,...,8,1630,0,1912,0,1710,3600,0,2014,9
825069097,1764,3029,770000.0,3,2.50,2650,40705,2.0,0,0,...,9,2650,0,1994,0,2550,42625,0,2014,6
1099600250,2242,6585,260000.0,3,1.75,1710,6400,1.0,0,0,...,7,1240,470,1976,0,1600,6400,0,2014,12
1189000207,2308,7861,387000.0,2,2.50,1170,1394,2.0,0,0,...,8,1170,0,2001,0,1250,3136,0,2014,10
1522700060,4535,10395,518000.0,4,2.75,2520,14021,2.0,0,0,...,9,2520,0,1999,0,2330,14007,0,2014,6
1622049154,2134,8879,289900.0,3,1.75,1899,11325,2.0,0,0,...,7,1899,0,1943,2005,2000,10454,62,2014,12
1788800910,939,12610,190000.0,3,1.00,1200,10458,1.0,0,0,...,6,1200,0,1961,0,1160,9000,0,2014,10
1951600150,4213,12993,180000.0,3,1.00,1610,8500,1.5,0,0,...,7,1610,0,1959,0,1070,8750,0,2015,4
2131701075,3942,13185,420000.0,3,1.75,1720,5000,1.5,0,0,...,8,1720,0,1932,2009,1410,8300,77,2014,12
2768100205,4929,19379,519000.0,4,2.50,1950,2617,1.5,0,0,...,7,1250,700,1910,0,1520,1438,0,2014,6
3123049142,280,6951,452000.0,3,2.25,2600,14810,1.0,0,2,...,8,1490,1110,1956,0,2450,16715,0,2014,8
3303980210,3317,18731,1115000.0,4,3.75,4040,14212,2.0,0,0,...,11,4040,0,2002,0,3940,14212,0,2015,4
3889100029,1611,6880,810000.0,3,2.50,2670,10481,2.0,0,0,...,9,2670,0,2003,0,2620,8895,0,2014,6
3995700435,1384,11107,265000.0,4,3.00,1940,8170,1.0,0,0,...,7,1940,0,1948,0,1310,8169,0,2014,7
5083000375,4332,3033,170000.0,3,1.00,1310,9529,1.0,0,0,...,7,1310,0,1956,0,1330,9529,0,2014,10
5083000375,4332,3034,235000.0,3,1.00,1310,9529,1.0,0,0,...,7,1310,0,1956,0,1330,9529,0,2015,3
5104540330,3498,7560,679000.0,4,2.50,3680,7236,2.0,0,0,...,10,3680,0,2006,0,3310,7180,0,2015,5
5428000070,2295,20765,770000.0,5,3.50,4750,8234,2.0,0,2,...,10,3350,1400,2013,0,2160,14496,0,2015,5
6131600255,4236,16228,202500.0,3,2.00,1540,8316,1.0,0,0,...,6,1540,0,1954,0,1250,8316,0,2014,12
6306800010,20,20288,436472.0,4,2.50,2692,8392,2.0,0,0,...,9,2692,0,2014,0,2574,14446,0,2014,8
6821600300,2866,4660,886000.0,3,2.25,2380,6000,2.0,0,0,...,9,1650,730,1931,0,2000,6000,0,2015,3
6823100225,4684,15505,700000.0,4,1.75,1870,6000,1.0,0,0,...,8,1670,200,1949,0,1710,6000,0,2015,4
7137950720,2765,13827,339100.0,4,2.50,2350,10655,2.0,0,0,...,8,2350,0,1992,0,2210,7028,0,2015,3
7731100066,2260,7447,545000.0,3,1.00,1510,5000,1.5,0,0,...,7,1510,0,1909,0,1680,4000,0,2014,6
7920100025,3475,2865,450000.0,2,1.00,740,5100,1.0,0,0,...,7,740,0,1947,0,920,5100,0,2015,4
8100400160,3840,1362,700000.0,3,2.25,2330,11424,2.0,0,0,...,8,2330,0,1984,0,2050,11448,0,2015,4
8146100580,1727,13635,765000.0,3,1.00,1220,7585,1.0,0,0,...,7,1220,0,1954,0,1380,8918,0,2014,10
8563000110,2068,17746,427000.0,4,1.75,1460,9750,1.0,0,0,...,7,1460,0,1967,0,1820,9840,0,2015,4
8861700030,1589,10112,510000.0,3,1.50,2400,10275,1.0,0,0,...,8,1540,860,1964,0,2380,10125,0,2014,12
8965450190,1459,7314,295000.0,3,2.50,1500,3060,2.0,0,0,...,7,1500,0,1994,0,2700,7734,0,2015,2
9510920050,1472,16528,725000.0,3,2.50,2980,16996,2.0,0,0,...,10,2980,0,1992,0,2980,15438,0,2014,9
9524100196,1474,20781,239000.0,2,1.50,680,772,2.0,0,0,...,7,680,0,2005,0,690,1059,0,2014,11

### 2.2 Присоедините к таблице clients данные по домам через метод merge
Это нужно, чтобы понимать, какие дома покупались клиентами
house_id - это индексы датафрейма с домами

In [135]:
df.reset_index(inplace=True)
clients.reset_index(inplace=True)
clients.merge(df, left_on='house_id', right_on='id')

,house_id,client_id,id,index,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,sqft_living15,sqft_lot15,delta_renovated,yr_sale,month_sale
0,8965450190,1459,8965450190,7314,295000.0,3,2.50,1500,3060,2.0,...,7,1500,0,1994,0,2700,7734,0,2015,2
1,6823100225,4684,6823100225,15505,700000.0,4,1.75,1870,6000,1.0,...,8,1670,200,1949,0,1710,6000,0,2015,4
2,5104540330,3498,5104540330,7560,679000.0,4,2.50,3680,7236,2.0,...,10,3680,0,2006,0,3310,7180,0,2015,5
3,2131701075,3942,2131701075,13185,420000.0,3,1.75,1720,5000,1.5,...,8,1720,0,1932,2009,1410,8300,77,2014,12
4,1522700060,4535,1522700060,10395,518000.0,4,2.75,2520,14021,2.0,...,9,2520,0,1999,0,2330,14007,0,2014,6
5,1189000207,2308,1189000207,7861,387000.0,2,2.50,1170,1394,2.0,...,8,1170,0,2001,0,1250,3136,0,2014,10
6,6821600300,2866,6821600300,4660,886000.0,3,2.25,2380,6000,2.0,...,9,1650,730,1931,0,2000,6000,0,2015,3
7,7137950720,2765,7137950720,13827,339100.0,4,2.50,2350,10655,2.0,...,8,2350,0,1992,0,2210,7028,0,2015,3
8,9510920050,1472,9510920050,16528,725000.0,3,2.50,2980,16996,2.0,...,10,2980,0,1992,0,2980,15438,0,2014,9
9,6131600255,4236,6131600255,16228,202500.0,3,2.00,1540,8316,1.0,...,6,1540,0,1954,0,1250,8316,0,2014,12
10,5428000070,2295,5428000070,20765,770000.0,5,3.50,4750,8234,2.0,...,10,3350,1400,2013,0,2160,14496,0,2015,5
11,1788800910,939,1788800910,12610,190000.0,3,1.00,1200,10458,1.0,...,6,1200,0,1961,0,1160,9000,0,2014,10
12,8100400160,3840,8100400160,1362,700000.0,3,2.25,2330,11424,2.0,...,8,2330,0,1984,0,2050,11448,0,2015,4
13,3123049142,280,3123049142,6951,452000.0,3,2.25,2600,14810,1.0,...,8,1490,1110,1956,0,2450,16715,0,2014,8
14,6306800010,20,6306800010,20288,436472.0,4,2.50,2692,8392,2.0,...,9,2692,0,2014,0,2574,14446,0,2014,8
15,5083000375,4332,5083000375,3033,170000.0,3,1.00,1310,9529,1.0,...,7,1310,0,1956,0,1330,9529,0,2014,10
16,5083000375,4332,5083000375,3034,235000.0,3,1.00,1310,9529,1.0,...,7,1310,0,1956,0,1330,9529,0,2015,3
17,7920100025,3475,7920100025,2865,450000.0,2,1.00,740,5100,1.0,...,7,740,0,1947,0,920,5100,0,2015,4
18,1951600150,4213,1951600150,12993,180000.0,3,1.00,1610,8500,1.5,...,7,1610,0,1959,0,1070,8750,0,2015,4
19,809001400,3113,809001400,9369,925000.0,3,1.00,1630,3200,1.5,...,8,1630,0,1912,0,1710,3600,0,2014,9
20,339600110,4809,339600110,3351,395000.0,3,2.50,1610,3755,2.0,...,7,1610,0,1987,0,1300,3823,0,2014,9
21,1622049154,2134,1622049154,8879,289900.0,3,1.75,1899,11325,2.0,...,7,1899,0,1943,2005,2000,10454,62,2014,12
22,1099600250,2242,1099600250,6585,260000.0,3,1.75,1710,6400,1.0,...,7,1240,470,1976,0,1600,6400,0,2014,12
23,8563000110,2068,8563000110,17746,427000.0,4,1.75,1460,9750,1.0,...,7,1460,0,1967,0,1820,9840,0,2015,4
24,2768100205,4929,2768100205,19379,519000.0,4,2.50,1950,2617,1.5,...,7,1250,700,1910,0,1520,1438,0,2014,6
25,3995700435,1384,3995700435,11107,265000.0,4,3.00,1940,8170,1.0,...,7,1940,0,1948,0,1310,8169,0,2014,7
26,8861700030,1589,8861700030,10112,510000.0,3,1.50,2400,10275,1.0,...,8,1540,860,1964,0,2380,10125,0,2014,12
27,3303980210,3317,3303980210,18731,1115000.0,4,3.75,4040,14212,2.0,...,11,4040,0,2002,0,3940,14212,0,2015,4
28,7731100066,2260,7731100066,7447,545000.0,3,1.00,1510,5000,1.5,...,7,1510,0,1909,0,1680,4000,0,2014,6
29,8146100580,1727,8146100580,13635,765000.0,3,1.00,1220,7585,1.0,...,7,1220,0,1954,0,1380,8918,0,2014,10
30,825069097,1764,825069097,3029,770000.0,3,2.50,2650,40705,2.0,...,9,2650,0,1994,0,2550,42625,0,2014,6
31,3889100029,1611,3889100029,6880,810000.0,3,2.50,2670,10481,2.0,...,9,2670,0,2003,0,2620,8895,0,2014,6
32,9524100196,1474,9524100196,20781,239000.0,2,1.50,680,772,2.0,...,7,680,0,2005,0,690,1059,0,2014,11

## Условие 3: 3 задача
Составьте несколько сводных таблиц
### 3.1 Найдите среднюю стоимость домов в зависимости от количества спален
Отсортируйте от меньшей стоимости к большей

In [140]:
df.groupby('bedrooms').agg({'price': 'mean'}).round().sort_values(by='price')

              price
bedrooms
1          317643.0
2          401373.0
0          409504.0
3          466232.0
11         520000.0
4          635420.0
33         640000.0
5          786600.0
10         819333.0
6          825521.0
9          894000.0
7          951185.0
8         1105077.0

### 3.2 Найдите минимальную, среднюю и максимальную стоимости домов в зависимости от состояния дома

In [141]:
df.groupby('condition').agg({'price': ['min', 'mean', 'max']})

              price
                min           mean        max
condition
1           78000.0  334431.666667  1500000.0
2           80000.0  327287.145349  2555000.0
3           75000.0  542012.578148  7062500.0
4           89000.0  521200.390033  7700000.0
5          110000.0  612418.089359  3650000.0

### 3.3 Постройте таблицу с подсчетом количества домов в данных в зависимости от вида на набережную и оценкой вида

In [143]:
pd.crosstab(index=df['waterfront'], columns=df['view'], values=df['id'], aggfunc='count')

view              0      1      2      3      4
waterfront
0           19489.0  331.0  955.0  491.0  184.0
1               NaN    1.0    8.0   19.0  135.0

### 3.4 Каких домов в зависимости от этажности и количества спален больше?

In [155]:
pd.crosstab(index=df['floors'], columns=df['bedrooms'], values=df['id'], aggfunc='count', margins=True, margins_name='Total').fillna(0)

bedrooms,0,1,2,3,4,5,6,7,8,9,10,11,33,Total
floors,,,,,,,,,,,,,,
1.0,4.0,162.0,1951.0,5455.0,2383.0,605.0,104.0,9.0,5.0,0.0,1.0,0.0,1.0,10680
1.5,0.0,21.0,182.0,786.0,698.0,185.0,30.0,7.0,1.0,0.0,0.0,0.0,0.0,1910
2.0,6.0,12.0,497.0,3118.0,3682.0,775.0,119.0,19.0,6.0,4.0,2.0,1.0,0.0,8241
2.5,0.0,1.0,5.0,56.0,58.0,23.0,14.0,2.0,0.0,2.0,0.0,0.0,0.0,161
3.0,2.0,3.0,123.0,405.0,61.0,13.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,613
3.5,1.0,0.0,2.0,4.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,8
Total,13.0,199.0,2760.0,9824.0,6882.0,1601.0,272.0,38.0,13.0,6.0,3.0,1.0,1.0,21613

In [167]:
df.groupby(['bedrooms', 'floors']).agg({'id': 'count'}).max()

id    5455
dtype: int64

### 3.5 Постройте таблицу с подсчетом медианной стоимости домов в данных в зависимости от состояния дома и оценки дома

In [171]:
pd.crosstab(index=df['condition'], columns=df['grade'], values=df['price'], aggfunc='median', margins=True, margins_name='Total').fillna(0)

grade,1,3,4,5,6,7,8,9,10,11,12,13,Total
condition,,,,,,,,,,,,,
1,142000.0,0.0,150000.0,190000.0,255000.0,403500.0,932500.0,0.0,0.0,0.0,0.0,0.0,262500.0
2,0.0,280000.0,145000.0,180000.0,235000.0,305000.0,429000.0,715000.0,1752500.0,0.0,0.0,0.0,279000.0
3,0.0,75000.0,205000.0,234475.0,265000.0,357500.0,485000.0,689000.0,890000.0,1209500.0,1807500.0,2888000.0,450000.0
4,0.0,0.0,238525.0,229975.0,295000.0,390000.0,571250.0,823500.0,1030000.0,1685000.0,2125000.0,5750000.0,440000.0
5,0.0,262000.0,0.0,227450.0,285475.0,456000.0,696000.0,1078000.0,1650000.0,2050000.0,1990000.0,0.0,526000.0
Total,142000.0,262000.0,205000.0,228700.0,275276.5,375000.0,510000.0,720000.0,914327.0,1284000.0,1817500.0,2983000.0,450000.0